variables:
  DOCKER_DRIVE: overlay2

image: docker:dind

services:
  - docker:dind

stages:
  - build

push_image:
  stage: build
  except:
    - master
  before_script:
    - apk update && apk add bash make git --update --no-caches
    - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
  script:
    - make image
    - make push
  after_script:
    - make clean

push_latest_image:
  stage: build
  only:
    - master
  before_script:
    - apk update && apk add bash make git --update --no-caches
    - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
  script:
    - make image
    - make push-all
  after_script:
    - make clean