variables:
  DOCKER_DRIVE: overlay2

image: node:10

stages:
  - build
  - push

build_image:
  stage: build
  before_script:
    - docker info
  script:
    - make image

push_image:
  stage: push
  except:
    - master
  before_script:
    - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
  script:
    - make push
  after_script:
    - make clean

push_latest_image:
  stage: push
  only:
    - master
  before_script:
    - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
  script:
    - make push-all
  after_script:
    - make clean